### ISSUE TITLE
Adding RobotOS imports causes Exception in thread, exited with -9 after successful program execution

### ISSUE THREAD

**Issue by fplk** [jdlangs/RobotOS.jl#88]
I use RobotOS in my SLAM module which I use from an agent module with the following imports:
```
import RobotOS: @rosimport, rostypegen, Publisher, publish, init_node, now
eachrow
@rosimport sensor_msgs.msg: PointCloud
@rosimport geometry_msgs.msg: Point32
@rosimport visualization_msgs.msg: Marker
rostypegen(@__MODULE__)
import .sensor_msgs.msg: PointCloud
import .geometry_msgs.msg: Point32
import .visualization_msgs.msg: Marker
```

Just adding these imports leads to an exception after my agent program has successfully executed and is about to terminate which looks like this [the number in Thread-10 varies between executions]:
```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/ai2thor/controller.py", line 782, in _start_unity_thread
    raise Exception("command: %s exited with %s" % (command, returncode))
Exception: command: ['/home/user/mitibm/AI2Thor_MCS/MCS-AI2-THOR-Unity-App-v0.1.0.x86_64', '-screen-fullscreen', '0', '-screen-quality', '3', '-screen-width', '600', '-screen-height', '400.0'] exited with -9
```

I'm not quite sure why this happens or how I can resolve this. Do you have any suggestions how to fix this or further insights into what causes this? I'm on Julia 1.5.1, Python 3.8.2, Ubuntu 20.04 and running this through VSCode with the Julia extension (running via Ctrl+5).

Thank you in advance.

**Comment by fplk** [comment]
I should add that `MCS-AI2-THOR-Unity-App-v0.1.0.x86_64` as the name implies is a Unity 3D environment that is called from Julia via PyCall. I assume that this threading error somehow relates to simultaneous threading for ROS and Unity which are launched from the same Julia program.
